[project]
name = "canary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
 dependencies = [
     "fastmcp>=2.12.4",
     "flask>=3.1.2",
     "mcp>=1.23.0",
     "mcp-agent>=0.2.6",
 ]

[tool.uv.workspace]
members = ["basic-agent"]
