[project]
name = "basic-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp-agent>=0.1.27",
    "openai>=1.109.1",
    "mcp==1.19.0"
]
